### ISSUE TITLE
你好，请问你说的个人用户申请实时音视频接口权限

### ISSUE THREAD

**Issue by by777** [AJLoveChina/wechat-pusher-player#3]
个人用户在主体类别里没有如IT、社交等类目了。你提了了一句个人用户可以申请，但是我现在看了好多，好像不行了。想咨询一下你当时申请此权限的步骤。谢谢。

**Comment by AJLoveChina** [comment]
我当时,  个人用户可以申请 小程序  实时音视频接口, 如果现在不行了,  就是微信政策条款变化.   根据我收到的一些私信, 应该是微信条款变化了, 不止你一个人有这样的问题。联系一下腾讯的客服， 建议打腾讯云电话客服， 电话容易打通， 表现出极强的音视频云服务购买期望 ：）
